GET http://localhost:5000/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "La La",
    "password": "123456"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "La La",
    "password": "123456"
}

###
PUT http://localhost:5000/api/auth/update/62fe3c66581bec815002a7ad HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo

{
    "username": "La La La",
    "score": 120
}

###
GET http://localhost:5000/api/post/62fc915fa8ae0e8f80524475
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo

###
GET http://localhost:5000/api/post/get/62fcc4eb8f9177041465a620
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo


###
POST http://localhost:5000/api/post/62fe44067af661f88879b747 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo


{
    "title": "Hi Hi",
    "content": "#Hi Hi H"
}

###
PUT http://localhost:5000/api/post/update/62fcc4eb8f9177041465a620 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJmZTVlYzI2YzI1M2VhNjFhMDE3YTYiLCJpYXQiOjE2NTY3NDM0MTd9.OB_YOTBPiyOYHRnAMYV08xn0k1g5bLHv0mc6nBhHEfU

{
    "title": "traditional music",
    "content": "very hila"
}

###

GET http://localhost:5000/api/course
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo

###
GET http://localhost:5000/api/course/62fe44067af661f88879b747
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo

###
POST http://localhost:5000/api/course HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo


{
    "title": "Đàn nguyệt",
    "description": "Nghe rất hay nha"
}

###
GET http://localhost:5000/api/course/public/
Content-Type: application/json

###
PUT http://localhost:5000/api/post/62bfe60f26c253ea61a017a9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJmZTVlYzI2YzI1M2VhNjFhMDE3YTYiLCJpYXQiOjE2NTY3NDM0MTd9.OB_YOTBPiyOYHRnAMYV08xn0k1g5bLHv0mc6nBhHEfU

{
    "title": "traditional music",
    "content": "very hila"
}