GET http://localhost:5000/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "VinhVinh",
    "password": "123456"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "VinhVinh",
    "password": "123456"
}

###
POST https://young-taiga-80393.herokuapp.com/api/auth/login
Content-Type: application/json

{
    "username": "VinhVinh",
    "password": "123456"
}

###
PUT http://localhost:5000/api/auth/update/62fe3c66581bec815002a7ad HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo

{
    "username": "La La La",
    "score": 120
}

###
GET http://localhost:5000/api/post/62fc915fa8ae0e8f80524475
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo

###
GET http://localhost:5000/api/post/get/62fcc4eb8f9177041465a620
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo


###
POST http://localhost:5000/api/post/6325fb980ee3afe80bee44c4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo


{
    "title": "Hi Hi",
    "content": "#Hi Hi H",
    "videoUrl": "https://www.youtube.com/watch?v=kJQP7kiw5Fk"
}

###
PUT http://localhost:5000/api/post/update/62fcc4eb8f9177041465a620 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJmZTVlYzI2YzI1M2VhNjFhMDE3YTYiLCJpYXQiOjE2NTY3NDM0MTd9.OB_YOTBPiyOYHRnAMYV08xn0k1g5bLHv0mc6nBhHEfU

{
    "title": "traditional music",
    "content": "very hila"
}

###

GET http://localhost:5000/api/course
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo

###
GET http://localhost:5000/api/course/62fe44067af661f88879b747
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZlM2M2NjU4MWJlYzgxNTAwMmE3YWQiLCJpYXQiOjE2NjA4Mjk0MzZ9.53qKVQLaR312pWn3nUGwdSwtJRyM6MYnGn0fGwc7Aqo

###
POST http://localhost:5000/api/course HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjZmNjJmZTFkMzAzNGNhMTlmYzUwZDgiLCJpYXQiOjE2NjM0MjMxODh9.DsNgQBC3Yo0XB40DIhzXKuN5FMeVgkcGK9DgSLGcffk


{
    "title": "Đàn nguyệt",
    "description": "Nghe rất hay nha",
    "imgUrl": "https://media.istockphoto.com/photos/koto-band-picture-id139696788?b=1&k=20&m=139696788&s=170667a&w=0&h=bfG6anYcReCQ8H6-f9JsWAHByXHW_-yKvvrfp4JDdE8="
}

###
GET http://localhost:5000/api/course/public/
Content-Type: application/json

###
PUT http://localhost:5000/api/course/update/6325d5f658160ad398b174a7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjZmNjJmZTFkMzAzNGNhMTlmYzUwZDgiLCJpYXQiOjE2NjM0MjMxODh9.DsNgQBC3Yo0XB40DIhzXKuN5FMeVgkcGK9DgSLGcffk

{
    "title": "Đàn Nguyệt",
    "description": "Nghe cũng hay đấy"

}

###
PUT http://localhost:5000/api/post/62bfe60f26c253ea61a017a9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJmZTVlYzI2YzI1M2VhNjFhMDE3YTYiLCJpYXQiOjE2NTY3NDM0MTd9.OB_YOTBPiyOYHRnAMYV08xn0k1g5bLHv0mc6nBhHEfU

{
    "title": "traditional music",
    "content": "very hila"
}